[controller]
control ip=192.168.0.x

[nodes]
node1 ip=192.168.0.x
node2 ip=192.168.0.x

[all:vars]
ansible_sudo_pass=secret

# Authentication: ldap, ad or none
auth_backend=ldap

# Windows Active Directory
ad_user=Administrator
ad_password=secret
ad_domain=ad.example.com

# Open LDAP
ldap_domain=example.com
ldap_org=example
ldap_password=secret
ldap_base_dn=dc=example,dc=com
ldap_admin_dn=cn=admin,dc=example,dc=com

# Slurm, Lmod, NFS
shared_dir=/home
shared_app=/opt
module_path=/opt/modulefiles
