[controller]
control ip=192.168.0.190

[nodes]
node1 ip=192.168.0.206
node2 ip=192.168.0.102

[all:vars]
ansible_sudo_pass=secret
ad_user=Administrator
ad_password=secret
ad_domain=ad.example.com
shared_dir=/home
shared_app=/opt
module_path=/opt/modulefiles
