---
#- import_playbook: playbooks/ad-controller.yml
- import_playbook: playbooks/pam-controller.yml
- import_playbook: playbooks/hostname-controller.yml
#- import_playbook: playbooks/etc-hosts.yml
#- import_playbook: playbooks/hostname-node.yml
- import_playbook: playbooks/nfs-controller.yml
- import_playbook: playbooks/lmod-controller.yml
- import_playbook: playbooks/nfs-node.yml
- import_playbook: playbooks/lmod-node.yml
- import_playbook: playbooks/slurm-controller.yml
- import_playbook: playbooks/slurm-node.yml
