[local]
localhost ansible_connection=local

[local:vars]
#ansible_ssh_user=user
#ansible_ssh_pass=secret
disk=/dev/sda

# All Simlab Computers
[simlab:children]
pcf
supermicro
pch

# PCF: Dell Precision T7500
[pcf]
simlab-f1.dhcp.uhasselt.be
simlab-f2.dhcp.uhasselt.be
simlab-f3.dhcp.uhasselt.be
simlab-f4.dhcp.uhasselt.be

[pcf:vars]
ansible_ssh_user=remote
#ansible_ssh_pass=secret
ansible_sudo_pass=secret
cpu=4
disk=/dev/sda

# Supermicros
[supermicro]
simlab-s2.dhcp.uhasselt.be
simlab-s3.dhcp.uhasselt.be
simlab-s4.dhcp.uhasselt.be
simlab-s5.dhcp.uhasselt.be

[supermicro:vars]
ansible_ssh_user=remote
#ansible_ssh_pass=secret
ansible_sudo_pass=secret
cpu=8
disk=/dev/sdb

# PCH: HP Elite Tower 800 G9
[pch]
simlab-h1.dhcp.uhasselt.be
simlab-h2.dhcp.uhasselt.be
simlab-h3.dhcp.uhasselt.be
simlab-h4.dhcp.uhasselt.be

[pch:vars]
ansible_ssh_user=remote
#ansible_ssh_pass=secret
ansible_sudo_pass=secret
cpu=32
disk=/dev/nvme0n1

# Temporary device
[temp]
simlab-f1.dhcp.uhasselt.be

[temp:vars]
ansible_ssh_user=remote
#ansible_ssh_pass=secret
ansible_sudo_pass=secret
cpu=4
#disk=/dev/nvme0n1
