id: ansible-ssh
namespace: ansible
description: Share ssh key with host.

inputs:
  - id: hosts
    displayName: "Hosts (comma separated)"
    type: STRING
    defaults: simlab
  - id: user
    displayName: "Host user (also used to ssh into machine)"
    type: STRING
    defaults: remote

tasks:
  - id: ansible_task
    type: io.kestra.plugin.ansible.cli.AnsibleCLI
    ansibleConfig: |
      [defaults]
      interpreter_python = auto_silent
    inputFiles:
      inventory.ini: "{{ read('inventory.ini') }}"
      playbook.yml: |
        ---
        - name: Set up ssh key between host and remote
          hosts: {{ inputs.hosts }}
          become: yes
          tasks:
            - name: Copy over public ssh key
              authorized_key:
                user: {{ user }}
                state: present
                key: "{{ read('id_rsa.pub') }}"
      id_rsa: "{{ read('id_rsa') }}"
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      pullPolicy: IF_NOT_PRESENT
      user: "1000"
    containerImage: cytopia/ansible:latest-tools
    commands:
      - ansible-playbook -i inventory.ini --key-file id_rsa playbook.yml
    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"