id: ansible-smtp
namespace: ansible
description: |
  Set up SMTP mail server and smartmontool on a Debian-based system.
  Required to be notified on a failing drive.

inputs:
  - id: hosts
    displayName: "Hosts (comma separated)"
    type: STRING
    defaults: simlab
  - id: email
    displayName: "E-mail used to send mails"
    type: STRING
    defaults: email@gmail.com
  - id: password
    displayName: "App password used to send mails"
    type: STRING
    defaults: secret

tasks:
  - id: ansible_task
    type: io.kestra.plugin.ansible.cli.AnsibleCLI
    ansibleConfig: |
      [defaults]
      interpreter_python = auto_silent
    namespaceFiles:
      enabled: true
      include:
        - inventory.ini
        - playbooks/smtp.yml
        - id_rsa
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      pullPolicy: IF_NOT_PRESENT
      user: "1000"
    containerImage: cytopia/ansible:latest-tools
    commands:
      - ansible-playbook -i inventory.ini --key-file id_rsa --extra-vars "target={{ inputs.hosts }} email={{ inputs.email }} password={{ inputs.password }}" playbooks/smtp.yml
    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"
