#+title: Deluge
#+property: header-args :tangle docker-compose.yml

Deluge is a lightweight, Free Software, cross-platform BitTorrent client. -<https://www.deluge-torrent.org/>

** Docker-compose.yml
*** Docker Image

- Docker Service Name = lscr.io/linuxserver/deluge:latest
- Image: Specify the docker image. No version behind colon so always latest version.
- Container_name: Name that will be given to the container. If not stated, this will be randomized.

#+begin_src yaml
version: '2.1'

services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
#+end_src

*** General

- Restart: The container will always try to restart unless it is manually stopped by the user.

#+begin_src yaml
    restart: unless-stopped
#+end_src

*** Network

- Ports: This is the port used by qBittorrent. Left is the host port, right is the container port.

#+begin_src yaml
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
#+end_src

*** Variables

- Volumes: Storage volumes need to be passed trough or keep locally. Left volume is a local directory or file. Right volume is a direcotry or file inside the container.
  - The movies and tv host path need to be the same as Sonarr and Radarr
- Environment: Add timezone, give same id as your user id ~$ id <username>~. Logs are optional.

#+begin_src yaml
    volumes:
      - </path/to/host/config>:/config
      - </path/to/host/Downloads>:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - DELUGE_LOGLEVEL=error
#+end_src

** Notes
- Default password is "deluge"
  - When prompted - change (preferences - interface)
- Preference:
  - Downloads save path: /downloads
  - Plugins: add Labels if you want to use radarr and sonarr
