#+title: Minecraft
#+property: header-args :tangle docker-compose.yml

This docker image provides a Minecraft Server that will automatically download the latest stable version at startup. -<https://github.com/itzg/docker-minecraft-server/blob/master/README.md>

** Prerequisites

- Minecraft client (& login)

** Docker-compose.yml
*** Docker Image

- Docker Service Name = minecraft
- Image: Specify the docker image. No version behind the colon so it will use the latest version.
- Container_name: Name that will be given to the container. If not stated, this will be randomized.

#+begin_src yaml
version: '3'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
#+end_src

*** General

- Restart: The container will always try to restart unless it is manually stopped by the user.
- Tty & stdin_open: Needed to run process in interactive mode.

#+begin_src yaml
    restart: unless-stopped
    tty: true
    stdin_open: true
#+end_src

*** Network

- Ports: 25565 is by default used for minecraft servers.

#+begin_src yaml
    ports:
      - 25565:25565
#+end_src

*** Variables

- Volumes: Multiple volumes need to be passed trough or keep locally. Left volume is a local directory or file. Right volume is a direcotry or file inside the container.
  - data is the saved minecraft world.
- Environment:
  - Accept the EULA.
  - Specify a specific type of minecraft server.
  - Admins of the server.
  - Enable whitelist or not and wether to enforce it or not.

#+begin_src yaml
    volumes:
      - </path/to/host/data>:/data
      - </path/to/host/plugins>:/plugins
    environment:
      EULA: "TRUE"
      #TYPE: "BUKKIT"
      OPS: "<Minecraft Username>"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
#+end_src

** Usage

- Connect to server via ~<host ip>:25565~
