---
- name: Join active directory as controller
  hosts: controller
  become: yes
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - realmd
          - sssd
          - sssd-tools
          - libnss-sss
          - libpam-sss
          - samba-common-bin
          - adcli
          - python3-pexpect

#   If rdns is disabled on the active directory
#   - name: Preconfigure some krb5.conf settings
#     ansible.builtin.blockinfile:
#       path: /etc/krb5.conf
#       create: yes
#       block: |
#         [libdefaults]
#           rdns = false
#           default_realm = {{ ad_domain|upper }}
#           udp_preference_limit = 0
#       marker: "# {mark} ANSIBLE MANAGED"
#
#   - name: Set permissions on krb5.conf
#     ansible.builtin.file:
#       path: /etc/krb5.conf
#       owner: root
#       group: root
#       mode: "0644"

    - name: Check realm status
      ansible.builtin.command: realm list
      register: realm_status
      changed_when: false

    - name: Join active directory
      ansible.builtin.expect:
        command: realm join --user={{ ad_user }} {{ ad_domain }}
        responses:
          '.*Password.*:': '{{ ad_password }}'
      when: ad_domain not in realm_status.stdout
