---
- name: Configure NFS Client
  hosts: nodes
  become: yes
  tasks:
    - name: Install nfs-common package
      ansible.builtin.apt:
        name: nfs-common
        state: present

    - name: Create nfs directory
      ansible.builtin.file:
        path: "{{ shared_dir }}"
        state: directory
        mode: "0755"

    - name: Mount the nfs share and ensure it is in fstab
      ansible.posix.mount:
        src: "{{ groups['controller'][0] }}:{{ shared_dir }}"
        path: "{{ shared_dir }}"
        fstype: nfs
        opts: "defaults,bg,_netdev,noatime,nodiratime,hard,intr"
        state: mounted
