services:
  calibre-web-automated-book-downloader:
    image: ghcr.io/calibrain/calibre-web-automated-book-downloader:latest
    environment:
      FLASK_PORT: 8084
      FLASK_DEBUG: false
      BOOK_LANGUAGE: en
    ports:
      - 8084:8084
    restart: unless-stopped
    volumes:
      - <path/to/books/ingest>:/cwa-book-ingest
