---
- name: Install RStudio
  hosts: controller
  become: true
  vars:
    release: "{{ ansible_distribution_release|lower}}"
    version: "2025.05.1-513"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install gdebi
      ansible.builtin.apt:
        name: gdebi
        state: present

    - name: Get Rsudio Server
      ansible.builtin.get_url:
        url: "https://download2.rstudio.org/server/{{ release }}/amd64/rstudio-server-{{version}}-amd64.deb"
        dest: "/tmp/rstudio.deb"

    - name: Install RStudio Server
      ansible.builtin.command:
        cmd: "/usr/bin/gdebi --non-interactive /tmp/rstudio.deb"

    # Be sure to have R version installed
    - name: Get list of installed R versions
      ansible.builtin.find:
        paths: /opt/apps/R/
        file_type: directory
      register: r_versions

    - name: Debug found directories
      debug:
        var: r_versions.files | map(attribute='path') | list

    - name: Set full R binary path
      set_fact:
        r_binary_path: >-
          /opt/apps/R/{{ (r_versions.files
          | map(attribute='path')
          | map('basename')
          | select('match', '^[0-9]+\.[0-9]+\.[0-9]+$')
          | sort
          | last) }}/bin/R

    - name: Add R binary path to rserver.conf
      ansible.builtin.lineinfile:
        path: /etc/rstudio/rserver.conf
        line: "rsession-which-r={{ r_binary_path }}"
        create: yes
        state: present
        insertafter: EOF

    # Might need to run this manually
    - name: Start RStudio Server
      ansible.builtin.command:
        cmd: "rstudio-server start"
