#+title: snipe-it
#+property: header-args :tangle docker-compose.yml

This boilerplate is mainly used for webserving.

** Docker-compose.yml
*** Docker Image

- Docker Service Name = snipeit
- Image: Specify the docker image and behind the colon the tag used. This is the version.
- Container_name: Name that will be given to the container. If not stated, this will be randomized.

#+begin_src yaml
version: '2.1'

services:
  snipeit:
    image: lscr.io/linuxserver/snipe-it:latest
    container_name: snipe-it
#+end_src

*** General

- Restart: The container will always try to restart unless it is manually stopped by the user.

#+begin_src yaml
    restart: unless-stopped
    depends_on:
      - mysql
#+end_src

*** Network

- Networks:
  - Ports: This is the port used for the website. It's recommended that you choose something other then port 80.

#+begin_src yaml
    ports:
      - <chosen port>:80
#+end_src

*** Variables

- Volumes: The config is used for persistent data so that everything can be easily updated. This is not required since you can always request a backup from inside the web-application.
- Environment: There will all be used to set up snipe-it. Set an initial username and password. The database name and username and password should match the mysql variables. The port from the APP_URL should also match the one give for the container port.


#+begin_src yaml
    volumes:
      - </path/to/host/config>:/config
    environment:
      - PUID=<$ id u>
      - PGID=<$ id g>
      - APP_ENV=production
      - APP_URL=http://<local ip-address>:<port>
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=<database name>
      - MYSQL_USER=<username>
      - MYSQL_PASSWORD=<password>
      - TZ=Europe/Brussels
      - MAIL_PORT_587_TCP_ADDR=smtp.gmail.com
      - MAIL_PORT_587_TCP_PORT=587
      - MAIL_ENV_USERNAME=<email>
      - MAIL_ENV_PASSWORD=<google app password>
      - MAIL_ENV_ENCRYPTION=tls
      - MAIL_ENV_FROM_ADDR=<email>
      - MAIL_ENV_FROM_NAME="<name>"
#+end_src

* MySQL
** Docker-compose.yml
*** Docker Image

- Image: Specify the docker image and behind the colon the tag used. This is the version.
- Container_name: Name that will be given to the container. If not stated, this will be randomized.

MySQL is used as the database that is used by snipe-it.

#+begin_src yaml
  mysql:
    image: mysql:5
    container_name: snipe_mysql
#+end_src

*** General

- Restart: The container will always try to restart unless it is manually stopped by the user.

#+begin_src yaml
    restart: always
#+end_src

*** Variables

- Volumes: Persistent data useful when updating container.
- Environment: These variables should be the same as given for snipe-it.

#+begin_src yaml
    volumes:
      - </path/to/host/data>:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<root password>
      - MYSQL_USER=<username>
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=<database name>
#+end_src

** Extras
- backups
