#+title: DuckDNS
#+property: header-args :tangle docker-compose.yml

Duck DNS free dynamic DNS hosted on Amazon VPC.

** Prerequisites

- A DuckDNS domain and token

** Docker-compose.yml
*** Docker Image

- Docker Service Name = duckdns
- Image: Specify the docker image and behind the colon the tag used. This is the version.
- Container_name: Name that will be given to the container. If not stated, this will be randomized.

#+begin_src yaml
version: '3 '

services:
  duckdns:
    image: linuxserver/duckdns:latest
    container_name: duckdns
#+end_src

*** General

- Restart: The container will always try to restart unless it is manually stopped by the user.

#+begin_src yaml
    restart: unless-stopped
#+end_src

*** Variables

- Volumes: Volume need to be passed trough or keep locally. Left volume is a local directory or file. Right volume is a directory or file inside the container.
- Environments:
  - User and group ID
  - Timezone
  - All DuckDNS subdomains you want to keep updated
  - Your DuckDNS Token
  - If you want to keep logs, enable LOG_FILE (volume needed)

#+begin_src yaml
    volumes:
      - </path/to/host/config>:/config
    environment:
      - PUID=<$ id -u>
      - PGID=<$ id -g>
      - TZ=Europe/Brussels
      - SUBDOMAINS=<duckdns subdomain1>,<subdomain2>
      - TOKEN=<duckdns token>
      - LOG_FILE=false
#+end_src
